export const plans = [
  {
    title: "Basic",
    monthly: "92 DZD",
    yearly: "1100 DZD",
    features: [
      { label: "Contacts", included: true },
      { label: "Basic Search", included: true },
      { label: "Norme madani", included: true },
      { label: "Antécédents / Archives", included: false },
      { label: "Storage 50 MB", included: true },
      {
        label: "Automatic Backup: 1 GB (150 D.A / Account / month)",
        included: false,
      },
      { label: "Calendar", included: false },
      { label: "Online doc modification", included: false },
      { label: "Mobile synchronization", included: false },
      { label: "Outlook synchronization", included: false },
    ],
  },
  {
    title: "Basic +",
    monthly: "200 DZD",
    yearly: "2400 DZD",
    features: [
      { label: "Contacts", included: true },
      { label: "Calendar", included: true },
      { label: "Basic Search", included: true },
      { label: "Norme madani", included: true },
      { label: "Antécédents / Archives", included: true },
      { label: "Storage 1GB", included: true },
      {
        label: "Automatic Backup: 1 GB (150 D.A / Account / month)",
        included: false,
      },
      { label: "Online doc modification", included: false },
      { label: "Mobile synchronization", included: false },
      { label: "Outlook synchronization", included: false },
      { label: "Custom filtering", included: false },
    ],
  },
  {
    title: "Standard",
    monthly: "300 DZD",
    yearly: "3600 DZD",
    features: [
      { label: "Contacts", included: true },
      { label: "Calendar", included: true },
      { label: "Advanced", included: true },
      { label: "Basic Search", included: true },
      { label: "Norme madani", included: true },
      { label: "Antécédents / Archives", included: true },
      { label: "Storage 2GB", included: true },
      {
        label: "Automatic Backup: 1 GB (150 D.A / Account / month)",
        included: false,
      },
      { label: "Online doc modification", included: true },
      { label: "Mobile synchronization", included: false },
      { label: "Outlook synchronization", included: false },
    ],
  },
  {
    title: "Home Professionnel",
    monthly: "500 DZD",
    yearly: "6000 DZD",
    features: [
      { label: "Contacts", included: true },
      { label: "Calendar", included: true },
      { label: "Basic Search", included: true },
      { label: "Norme madani_Archive", included: true },
      { label: "Mobile synchronization", included: true },
      { label: "Online doc modification", included: true },
      { label: "Antécédents / Archives", included: true },
      { label: "Advanced", included: true },
      { label: "Custom filtering", included: true },
      { label: "Outlook synchronization", included: true },
      {
        label: "Backup Storage + (5 GB to 150 D.A / Account / month)",
        included: true,
      },
    ],
  },
];
